name: PR Preview Deploy

on:
  workflow_run:
    workflows: ['PR Preview Build']
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: ðŸ“¥ Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: preview-build
          path: .
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ“– Read PR number
        id: pr
        run: echo "number=$(cat pr_number.txt)" >> $GITHUB_OUTPUT

      - name: ðŸš€ Deploy preview
        env:
          PULL_NUMBER: ${{ steps.pr.outputs.number }}
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.PREVIEW_SSH_PRIVATE_KEY }}"
          rsync -r --delete --rsync-path="mkdir -p ${{ vars.PREVIEW_HOST_TARGET_DIR }}/$PULL_NUMBER && rsync" -e "ssh -o StrictHostKeyChecking=no" ./build/ ${{ vars.PREVIEW_HOST_USERNAME }}@${{ vars.PREVIEW_HOST_IP }}:${{ vars.PREVIEW_HOST_TARGET_DIR }}/$PULL_NUMBER

      - name: ðŸŒ Comment preview URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const prNumber = parseInt('${{ steps.pr.outputs.number }}');
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });
            const existingComment = comments.find(comment => comment.body.includes('Preview is ready! ðŸš€'));
            if (!existingComment) {
              const body = `Preview is ready! ðŸš€ You can view it here: https://valhalla-app-tests.gis-ops.com/${prNumber}`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
              console.log('Comment created successfully');
            } else {
              console.log('Comment already exists');
            }
