name: PR Preview Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - 'docker*'
      - 'Docker*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ“ Save PR number
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: ğŸ  Replace homepage URL
        run: sed -i "s/https:\/\/valhalla.openstreetmap.de/https:\/\/valhalla-app-tests.gis-ops.com\/${{ github.event.pull_request.number }}/g" package.json

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: ğŸ”§ Install and build
        run: |
          npm ci
          npm run build

      - name: ğŸ“¦ Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-build
          path: |
            ./build
            pr_number.txt
          retention-days: 1
